// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	entities "task-management-api/domain/entities"

	mock "github.com/stretchr/testify/mock"

	model "task-management-api/domain/model"
)

// AuthUseCase is an autogenerated mock type for the AuthUseCase type
type AuthUseCase struct {
	mock.Mock
}

// AdminRegister provides a mock function with given fields: currUser, userCreate, param
func (_m *AuthUseCase) AdminRegister(currUser entities.AuthenticatedUser, userCreate *model.UserCreate, param interface{}) (*model.UserInfo, string, error) {
	ret := _m.Called(currUser, userCreate, param)

	if len(ret) == 0 {
		panic("no return value specified for AdminRegister")
	}

	var r0 *model.UserInfo
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(entities.AuthenticatedUser, *model.UserCreate, interface{}) (*model.UserInfo, string, error)); ok {
		return rf(currUser, userCreate, param)
	}
	if rf, ok := ret.Get(0).(func(entities.AuthenticatedUser, *model.UserCreate, interface{}) *model.UserInfo); ok {
		r0 = rf(currUser, userCreate, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(entities.AuthenticatedUser, *model.UserCreate, interface{}) string); ok {
		r1 = rf(currUser, userCreate, param)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(entities.AuthenticatedUser, *model.UserCreate, interface{}) error); ok {
		r2 = rf(currUser, userCreate, param)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Login provides a mock function with given fields: currUser, userLogin, param
func (_m *AuthUseCase) Login(currUser entities.AuthenticatedUser, userLogin *model.UserLogin, param interface{}) (entities.Token, string, error) {
	ret := _m.Called(currUser, userLogin, param)

	if len(ret) == 0 {
		panic("no return value specified for Login")
	}

	var r0 entities.Token
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(entities.AuthenticatedUser, *model.UserLogin, interface{}) (entities.Token, string, error)); ok {
		return rf(currUser, userLogin, param)
	}
	if rf, ok := ret.Get(0).(func(entities.AuthenticatedUser, *model.UserLogin, interface{}) entities.Token); ok {
		r0 = rf(currUser, userLogin, param)
	} else {
		r0 = ret.Get(0).(entities.Token)
	}

	if rf, ok := ret.Get(1).(func(entities.AuthenticatedUser, *model.UserLogin, interface{}) string); ok {
		r1 = rf(currUser, userLogin, param)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(entities.AuthenticatedUser, *model.UserLogin, interface{}) error); ok {
		r2 = rf(currUser, userLogin, param)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// Register provides a mock function with given fields: currUser, userCreate, param
func (_m *AuthUseCase) Register(currUser entities.AuthenticatedUser, userCreate *model.UserCreate, param interface{}) (*model.UserInfo, string, error) {
	ret := _m.Called(currUser, userCreate, param)

	if len(ret) == 0 {
		panic("no return value specified for Register")
	}

	var r0 *model.UserInfo
	var r1 string
	var r2 error
	if rf, ok := ret.Get(0).(func(entities.AuthenticatedUser, *model.UserCreate, interface{}) (*model.UserInfo, string, error)); ok {
		return rf(currUser, userCreate, param)
	}
	if rf, ok := ret.Get(0).(func(entities.AuthenticatedUser, *model.UserCreate, interface{}) *model.UserInfo); ok {
		r0 = rf(currUser, userCreate, param)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.UserInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(entities.AuthenticatedUser, *model.UserCreate, interface{}) string); ok {
		r1 = rf(currUser, userCreate, param)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(entities.AuthenticatedUser, *model.UserCreate, interface{}) error); ok {
		r2 = rf(currUser, userCreate, param)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewAuthUseCase creates a new instance of AuthUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthUseCase {
	mock := &AuthUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
