// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Environment is an autogenerated mock type for the Environment type
type Environment struct {
	mock.Mock
}

// GetDbName provides a mock function with given fields:
func (_m *Environment) GetDbName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDbName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetDbURL provides a mock function with given fields:
func (_m *Environment) GetDbURL() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDbURL")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetJwtKey provides a mock function with given fields:
func (_m *Environment) GetJwtKey() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetJwtKey")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// GetPort provides a mock function with given fields:
func (_m *Environment) GetPort() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPort")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewEnvironment creates a new instance of Environment. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewEnvironment(t interface {
	mock.TestingT
	Cleanup(func())
}) *Environment {
	mock := &Environment{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
