// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	"context"
	"task-management-api/domain/entities"
	"github.com/stretchr/testify/mock"
	"task-management-api/domain/model"
)

// TaskUsecase is an autogenerated mock type for the TaskUsecase type
type TaskUsecase struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: newTask
func (_m *TaskUsecase) CreateTask(newTask entities.Task) error {
	ret := _m.Called(newTask)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(entities.Task) error); ok {
		r0 = rf(newTask)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteTask provides a mock function with given fields: id, userID
func (_m *TaskUsecase) DeleteTask(id string, userID string) error {
	ret := _m.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(id, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetTaskByID provides a mock function with given fields: ctx, id, userID
func (_m *TaskUsecase) GetTaskByID(ctx context.Context, id string, userID string) (*model.TaskInfo, error) {
	ret := _m.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskByID")
	}

	var r0 *model.TaskInfo
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (*model.TaskInfo, error)); ok {
		return rf(ctx, id, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) *model.TaskInfo); ok {
		r0 = rf(ctx, id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TaskInfo)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = rf(ctx, id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetTasks provides a mock function with given fields:
func (_m *TaskUsecase) GetTasks() (*[]*model.TaskInfo, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetTasks")
	}

	var r0 *[]*model.TaskInfo
	var r1 error
	if rf, ok := ret.Get(0).(func() (*[]*model.TaskInfo, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *[]*model.TaskInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*[]*model.TaskInfo)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateTask provides a mock function with given fields: id, userID
func (_m *TaskUsecase) UpdateTask(id string, userID string) (*model.TaskUpdate, error) {
	ret := _m.Called(id, userID)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTask")
	}

	var r0 *model.TaskUpdate
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string) (*model.TaskUpdate, error)); ok {
		return rf(id, userID)
	}
	if rf, ok := ret.Get(0).(func(string, string) *model.TaskUpdate); ok {
		r0 = rf(id, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.TaskUpdate)
		}
	}

	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(id, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewTaskUsecase creates a new instance of TaskUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskUsecase {
	mock := &TaskUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
